//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace server
{
    using System;
    using System.Collections.Generic;
    
    public partial class lesson
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lesson()
        {
            this.attentions = new HashSet<attention>();
        }
    
        public int id { get; set; }
        public int user_id { get; set; }
        public System.DateTime date { get; set; }
        public string theme { get; set; }
        public int status_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<attention> attentions { get; set; }
        public virtual status status { get; set; }
        public virtual user user { get; set; }
    }
}
